CREATE DATABASE TELECOM_PORTFOLIO;
USE TELECOM_PORTFOLIO;

-- Import Datasets Tables : Orders, Product, customers, Customers usage.

SELECT * FROM ORDERS LIMIT 5;

/*

Order_id | Customer_id | Product_id | Order_date | Quantity 

1        | 850	       | 106	      | 02-05-2025 | 3
2        | 548	       | 101	      | 16-02-2024 | 2
3        | 612	       | 108	      | 04-09-2024 | 1
4        | 915	       | 108	      | 15-11-2025 | 2
5	       | 681	       | 107	      | 11-06-2025 | 2

*/



--SECTION 1 – CUSTOMER ANALYSIS

--#List all active customers.

SELECT
    C.CUSTOMER_ID,
    C.NAME,
    C.CITY,
    GROUP_CONCAT(
       P.PRODUCT_NAME
       ORDER BY O.ORDER_DATE DESC
       SEPARATOR ','
    ) AS PLAN_HISTORY,
    MAX(O.ORDER_DATE) AS ACTIVATION_DATE
FROM CUSTOMERS C
JOIN ORDERS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN PRODUCTS P
    ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY
    C.CUSTOMER_ID,
    C.NAME,
    C.CITY
ORDER BY C.CUSTOMER_ID;



--Find customers who have never placed an order.

SELECT
    C.CUSTOMER_ID,
    C.NAME,
    C.CITY
FROM CUSTOMERS C
LEFT JOIN ORDERS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE O.CUSTOMER_ID IS NULL
ORDER BY C.CUSTOMER_ID;


 --Identify top 10 customers by total spend.	
    
SELECT
    C.CUSTOMER_ID,
    C.NAME,
    C.CITY,
    SUM(O.QUANTITY * P.MONTHLY_PRICE) AS TOTAL_SPEND
FROM CUSTOMERS C
JOIN ORDERS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN PRODUCTS P
    ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    C.CUSTOMER_ID,
    C.NAME,
    C.CITY
ORDER BY
    TOTAL_SPEND DESC
LIMIT 10;

  
--Customers with NO usage activity in the last 90 days.

SELECT
    C.CUSTOMER_ID,
    C.NAME,
    C.CITY
FROM CUSTOMERS C
LEFT JOIN CUSTOMERS_USAGE U
    ON C.CUSTOMER_ID = U.CUSTOMER_ID
    AND U.MONTH >= CURDATE() - INTERVAL 90 DAY
WHERE U.CUSTOMER_ID IS NULL
ORDER BY C.CUSTOMER_ID;


--Segment customers into:
---	#High Usage: > 50 GB/month
---	#Medium Usage: 10–50 GB/month
---	#Low Usage: < 10 GB/month.

SELECT
   C.CUSTOMER_ID,
   C.NAME,
   C.CITY,
   ROUND(AVG(U.DATA_USED_GB),2) AS AVG_MONTHLY_USAGE,
   CASE 
       WHEN AVG(U.DATA_USED_GB) >50 THEN "HIGH USAGE"
       WHEN AVG(U.DATA_USED_GB) BETWEEN 10 AND 50 THEN "MEDIUM USAGE"
       ELSE "LOW USAGE"
	END AS USAGE_SEGMENT
FROM CUSTOMERS C
JOIN CUSTOMERS_USAGE U
     ON C.CUSTOMER_ID = U.CUSTOMER_ID
GROUP BY 
     C.CUSTOMER_ID,
     C.NAME,
     C.CITY
ORDER BY AVG_MONTHLY_USAGE DESC;



--SECTION 2 – REVENUE & SALES

--Calculate monthly revenue for the last 12 months.

SELECT
     DATE_FORMAT(O.ORDER_DATE, '%Y-%m') AS MONTH,
     SUM(O.QUANTITY * P.MONTHLY_PRICE) AS MONTHLY_REVENUE
FROM ORDERS O
JOIN PRODUCTS P
     ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE O.ORDER_DATE >=DATE_SUB(CURDATE(),INTERVAL 12 MONTH)
GROUP BY MONTH
ORDER BY MONTH;


--Find the top 5 best-selling products by:
---	#Total quantity sold.

SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(O.QUANTITY) AS TOTAL_QUANTITY_SOLD
FROM PRODUCTS P
JOIN ORDERS O
    ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME
ORDER BY
    TOTAL_QUANTITY_SOLD DESC
LIMIT 5;


---	#Total revenue generated.

SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(O.QUANTITY * P.MONTHLY_PRICE) AS TOTAL_REVENUE
FROM PRODUCTS P
JOIN ORDERS O
    ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME
ORDER BY
    TOTAL_REVENUE DESC
LIMIT 5;


--Identify products that have zero sales.

SELECT 
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.MONTHLY_PRICE
FROM PRODUCTS P
LEFT JOIN ORDERS O
    ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE O.PRODUCT_ID IS NULL
ORDER BY P.PRODUCT_ID;


--Show average order value (AOV) month by month.

SELECT 
   DATE_FORMAT(O.ORDER_DATE, '%Y-%m') AS MONTH,
   ROUND(AVG(O.QUANTITY * P.MONTHLY_PRICE)) AS AVG_ORDER_VALUE
FROM ORDERS O
JOIN PRODUCTS P
   ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY MONTH
ORDER BY MONTH;


--Determine top 5 city generates the highest revenue.

SELECT
    C.CITY,
    SUM(O.QUANTITY * P.MONTHLY_PRICE) AS REVENUE
    FROM CUSTOMERS C
JOIN ORDERS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN PRODUCTS P
    ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY
    C.CITY
ORDER BY 
    REVENUE DESC
LIMIT 5;


--SECTION 3 – CHURN & RETENTION

--Calculate monthly churn rate
--- #(Users active last month but not active this month)

WITH LAST_MONTH AS (
    SELECT DISTINCT
        CUSTOMER_ID
    FROM CUSTOMERS_USAGE
    WHERE DATE_FORMAT(MONTH, '%Y-%m') =
          DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 MONTH), '%Y-%m')
),
THIS_MONTH AS (
    SELECT DISTINCT
        CUSTOMER_ID
    FROM CUSTOMERS_USAGE
    WHERE DATE_FORMAT(MONTH, '%Y-%m') = DATE_FORMAT(CURDATE(), '%Y-%m')
)
SELECT
    (SELECT COUNT(*) FROM LAST_MONTH) AS TOTAL_ACTIVE_LAST_MONTH,
    (SELECT COUNT(*) 
     FROM LAST_MONTH  
     WHERE CUSTOMER_ID NOT IN (SELECT CUSTOMER_ID FROM THIS_MONTH)) 
        AS CHURNED_USERS,
    ROUND(
           (
            (SELECT COUNT(*) FROM LAST_MONTH WHERE CUSTOMER_ID NOT IN (SELECT CUSTOMER_ID FROM THIS_MONTH)) 
            / (SELECT COUNT(*) FROM LAST_MONTH)
		   ) * 100, 2
         ) AS MONTHLY_CHURN_RATE_PERCENT;
         


--Calculate customer lifetime value (CLV) using:
---#total revenue ÷ months active


SELECT
    C.CUSTOMER_ID,
    C.NAME,
    C.CITY,
    SUM(O.QUANTITY * P.MONTHLY_PRICE) AS TOTAL_REVENUE,
    COUNT(DISTINCT DATE_FORMAT(U.MONTH, '%Y-%m')) AS MONTHS_ACTIVE,
    ROUND(
        SUM(O.QUANTITY * P.MONTHLY_PRICE)
        / COUNT(DISTINCT DATE_FORMAT(U.MONTH, '%Y-%m')),
        2
    ) AS CLV
FROM CUSTOMERS C
JOIN ORDERS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN PRODUCTS P
    ON O.PRODUCT_ID = P.PRODUCT_ID
JOIN CUSTOMERS_USAGE U
    ON C.CUSTOMER_ID = U.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.NAME,
    C.CITY
ORDER BY
    CLV DESC;
    
    

--SECTION 4 – PRODUCT PERFORMANCE
--Rank products by revenue.
    
SELECT 
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(O.QUANTITY * P.MONTHLY_PRICE) AS TOTAL_REVENUE,
    RANK() OVER(
		ORDER BY SUM(O.QUANTITY * P.MONTHLY_PRICE) DESC
        ) AS REVENUE_RANK
FROM PRODUCTS P
JOIN ORDERS O 
	ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY 
    P.PRODUCT_ID,
    P.PRODUCT_NAME
ORDER BY
    REVENUE_RANK;
    
    
--Calculate product-wise:
---#	Average price sold.
---#	Total orders.
---#	Revenue contribution %.


SELECT 
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    ROUND(AVG(P.MONTHLY_PRICE), 2) AS AVERAGE_PRICE_SOLD,
    COUNT(O.ORDER_ID) AS TOTAL_ORDER,
    ROUND(
           (SUM(O.QUANTITY * P.MONTHLY_PRICE)
           /SUM(SUM(O.QUANTITY * P.MONTHLY_PRICE)) OVER()) * 100,2
         ) AS REVENUE_CONTRIBUTION_PERCENT
FROM PRODUCTS P
JOIN ORDERS O
    ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME
ORDER BY
    REVENUE_CONTRIBUTION_PERCENT DESC;



--Find products whose sales dropped compared to last month


WITH MONTHLY_PRODUCT_SALES AS (
    SELECT
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        DATE_FORMAT(O.ORDER_DATE, '%Y-%m') AS SALES_MONTH,
        SUM(O.QUANTITY * P.MONTHLY_PRICE) AS MONTHLY_REVENUE
    FROM PRODUCTS P
    JOIN ORDERS O
        ON P.PRODUCT_ID = O.PRODUCT_ID
    GROUP BY
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        SALES_MONTH
),
SALES_COMPARISON AS (
    SELECT
        PRODUCT_ID,
        PRODUCT_NAME,
        SALES_MONTH,
        MONTHLY_REVENUE,
        LAG(MONTHLY_REVENUE, 1) OVER (
            PARTITION BY PRODUCT_ID
            ORDER BY SALES_MONTH
        ) AS PREVIOUS_MONTH_REVENUE
    FROM MONTHLY_PRODUCT_SALES
)
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    PREVIOUS_MONTH_REVENUE,
    MONTHLY_REVENUE AS CURRENT_MONTH_REVENUE,
    ROUND(
        ((PREVIOUS_MONTH_REVENUE - MONTHLY_REVENUE)
         / PREVIOUS_MONTH_REVENUE) * 100,
        2
    ) AS SALES_DROP_PERCENT
FROM SALES_COMPARISON
WHERE
    PREVIOUS_MONTH_REVENUE IS NOT NULL
    AND MONTHLY_REVENUE < PREVIOUS_MONTH_REVENUE
ORDER BY
    SALES_DROP_PERCENT DESC;












